title: 4lch4
logo: ./assets/img/logo.png
description: The personal website for Alcha.
show_downloads: false
google_analytics: UA-127142225-1
repository: Alcha/alcha.github.io

email: alcha@hasslefree.solutions
url: 'https://alcha.org' # the base hostname & protocol for your site

# Social
githubUsername: Alcha
twitterUsername: 4lch4

themeColor: green # green, blue, orange, purple, grey
fixedNav: 'true' # true or false

permalink: /blog/:title
markdown: kramdown
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed

plugins:
  - jekyll-feed
